name: Deploy Documentation and Storybook

on:
  push:
    branches:
      - main
      - develop
    paths:
      - client/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "./client/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build documentation
        run: pnpm typedoc

      - name: Build storybook
        run: pnpm run build-storybook

      # Documentation 먼저 배포
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/docs
          destination_dir: ./
          keep_files: true
          commit_message: "chore: deploy storybook and documentation"
